import Image from 'next/image'
import MagneticButton from '../components/MagneticButton'

const releases=[['LR–001','A Place for Static','Mara Vale','LP · 1987'],['LR–004','River Circuit','North Window','12″ · 1991'],['LR–009','Rooms After Rain','Sevens','LP · 1996'],['LR–013','Held Frequencies','Oriel','7″ · 2003']]
const notes=[['Reel 04 / Side A','Drums kept from the room mic. No gate.'],['Reel 11 / Side B','A chair moving during the final chord remains.'],['Reel 18 / Take 2','The first complete take became the master.']]
export default function Page(){return <main>
  <header><a className="wordmark" href="#top">LOW ROOM</a><nav aria-label="Primary"><a href="#catalog">Catalog</a><a href="#room">The room</a><a href="#notes">Session notes</a></nav></header>
  <section className="hero" id="top"><div className="hero-copy"><h1>Recorded without polish.</h1><p>Low Room is an independent label archive for records made with the door shut, the tape rolling, and the imperfections left where they landed.</p><MagneticButton href="#catalog">Enter the catalog</MagneticButton></div><figure><Image src="/assets/analog-room.png" alt="An empty analog recording room with a mixing desk and reel-to-reel tape machines" width={1536} height={1024} priority/><figcaption>The recording room, preserved as working evidence rather than nostalgia.</figcaption></figure></section>
  <section className="manifesto"><h2>The room is part of the record.</h2><p>Bleed, floorboards, amplifier hum and the few seconds before a count-in are not defects to erase. They locate a performance in a real place.</p></section>
  <section className="catalog" id="catalog"><div><h2>Records in circulation</h2><p>A compact selection from the label’s fictional catalog, written as interface sample content rather than sales claims.</p></div><ol>{releases.map((r,i)=><li key={r[0]}><button type="button"><span>{String(i+1).padStart(2,'0')}</span><strong>{r[1]}</strong><em>{r[2]}</em><small>{r[3]}</small></button></li>)}</ol></section>
  <section className="room" id="room"><div className="tape"><span/><span/><i/></div><div><h2>One room. Four microphones.</h2><p>The archive’s visual system follows the same constraint as the sessions: fewer ingredients, placed carefully. The recording chain is shown as a plain route, not a claim of sonic superiority.</p><dl><dt>Source</dt><dd>Voice, strings, percussion</dd><dt>Capture</dt><dd>Four microphone positions</dd><dt>Medium</dt><dd>¼-inch tape</dd></dl></div></section>
  <section className="listening"><blockquote>“Leave the count-in.”</blockquote><div><h2>Listening instructions</h2><p>Play the record in sequence. Leave a little room around it. Headphones reveal the edits; speakers reveal the room.</p></div></section>
  <section className="notes" id="notes"><h2>What the tape box remembers</h2><div>{notes.map(n=><article key={n[0]}><h3>{n[0]}</h3><p>{n[1]}</p></article>)}</div></section>
  <section className="pressing"><div className="disc" aria-hidden="true"><i/></div><div><h2>From master reel to pressing</h2><p>The sequence stays short: edit with a blade, approve a reference cut, press the sides, return the master to its box.</p><ol><li>Edit the sequence</li><li>Cut the reference</li><li>Press the sides</li><li>Shelve the reel</li></ol></div></section>
  <section className="sleeves"><h2>Sleeves built from evidence</h2><p>Track sheets, room photographs, pencil marks and typewritten credits form the artwork. Nothing is added to suggest a history the object did not live.</p><div className="covers"><div>LOW<br/>ROOM<br/>001</div><div>A PLACE<br/>FOR<br/>STATIC</div><div>MASTER<br/>COPY</div></div></section>
  <section className="care"><h2>Care for the object</h2><div><p>Keep vinyl upright. Keep tape tails-out. Write on the box, not the reel. Store both away from heat and direct light.</p><p>For this regression site, catalog entries and session details are explicitly fictional sample editorial content.</p></div></section>
  <section className="closing"><h2>Begin with the first reel.</h2><MagneticButton href="#catalog">Browse the records</MagneticButton></section>
  <footer><strong>LOW ROOM RECORDS</strong><p>Independent label archive · design regression test</p><a href="#top">Back to the room ↑</a></footer>
  </main>}
